# Configuration

# -- 1. Where to do download the repo
src_path: ./src 
merida_repo: git@github.com:bhklab/MERIDA.git

# -- 2. Where to build the binary

## If you make this a directory on your $PATH you can run the command without
## specifying the install directory
bin_path: /home/ceeles/bin

# -- 3. Path to required packages

## This pipeline requires ILOG CPLEX, closed source software form IBM
## To install this software, register for an academic account with IBM
## and request a free academic licencse
## See: https://docs.computecanada.ca/wiki/CPLEX/en, 
## NOTE: You do not need to build the module if you are not on Compute Canada, 
## just specify the corret path tot the CPLEX_StudioXYZ directory for your 
## version
cplex_path: $CPLEX_HOME

# -- 4. Datasets to download
## TODO:: Implement data download and preprocesing
dataset: CCLE

# -- 5. Identifiers for this run of the pipeline
analysis_name: roche

# -- 6. Hyper parameter search space
# Passed to Python range function to make a sequence
M: {start: 2, stop: 64, step: 2}
v: [linear, quadratic, cubic]
threshold: 0.2
# Set to no or integer number of folds to cross validate over (e.g., 5)
cross_validation: 5

# -- 7. Input/output files for MERIDA
rawdata: /home/ceeles/development/MERIDA_snakemake_pipeline/rawdata
metadata: /home/ceeles/development/MERIDA_snakemake_pipeline/metadata
procdata: /home/ceeles/development/MERIDA_snakemake_pipeline/procdata
results: /home/ceeles/development/MERIDA_snakemake_pipeline/results

feature_matrix: CCLE_bimodal_genes.txt
response_vector: CCLE_erlotinib_AAC.txt

# null or path to preselected feature file, format must match MERIDA specificaitons
## NOTE:: This parameter has not been tested!
preselected_features: null

# -- 8. Slurm Header Configuration
cpu_per_job: 16
mem_per_job: 32G
runtime_per_job: "7-00:00:00"
slurm_output: /home/ceeles/development/MERIDA_snakemake_pipeline/logs/slurm-%j.out