# Configuration

# -- 1. Where to do download the repo
src_path: ./src 
merida_repo: git@github.com:bhklab/MERIDA.git

# -- 2. Where to build the binary

## If you make this a directory on your $PATH you can run the command without
## specifying the install directory
bin_path: /home/ceeles/bin

# -- 3. Path to required packages

## This pipeline requires ILOG CPLEX, closed source software form IBM
## To install this software, register for an academic account with IBM
## and request a free academic licencse
## See: https://docs.computecanada.ca/wiki/CPLEX/en, 
## NOTE: You do not need to build the module if you are not on Compute Canada, 
## just specify the corret path tot the CPLEX_StudioXYZ directory for your 
## version
cplex_path: $CPLEX_HOME

# -- 4. Datasets to download
## TODO::
dataset: CCLE

# -- 5. Identifiers for this run of the pipeline
analysis_name: roche

# -- 6. Hyper parameter search space
# Passed to Python range function to make a sequence
M: {start: 2, stop: 512, step: 2}
v: [linear, cubic, quadratic]
threshold: 0.2

# -- 7. Input/output files for MERIDA
feature_matrix: ./procdata/CCLE_bimodal_genes.txt
response_vector: ./procdata/CCLE_erlotinib_ACC.txt
out_dir: ./results

# -- 8. Slurm Header Configuration
